- name: setup database mysql server
  hosts: dbsrv
  become: true
  tasks:
    - name: installing mysql server
      yum:
        name: mariadb-server
        state: present

    - name: installing python mysql service
      yum:
        name: MySQL-python
        state: present

    - name: starting the mysql server
      service:
        name: mariadb
        state: started
        enabled: true

    - name: creating the database accounts
      mysql_db:
        name: "{{dbname}}"
        state: present
      register: db_out

    - name: creating the datases users
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL,GRANT'
        state: present
      register: keyout

    - debug:
        var: db_out

    - debug:
        var: keyout

