- name: setup database mysql server
  hosts: dbsrv
  become: true
  tasks:
    - name: installing mysql server
      yum:
        name: mariadb-server
        state: present

    - name: installing python mysql service
      yum:
        name: MySQL-python
        state: present

    - name: starting the mysql server
      service:
        name: mariadb
        state: started
        enabled: true

    - name: creating the database accounts
      mysql_db:
        name: accounts
        state: present

    - name: creating the datases users
      mysql_user:
        name: admin
        password: 12345
        priv: '*.*:ALL,GRANT'
        state: present


