- name: setup database mysql server
  hosts: dbsrv
  become: true
  tasks:
    - name: installing mysql server
      yum:
        name: mariadb-server
        state: present

    - name: starting the mysql server
      service:
        name: mariadb
        state: started
        enabled: true

    - name: creating the database accounts
      mysql_db:
        name: accounts
        state: present


